# Codecov configuration for Figgo
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        base: auto
    patch:
      default:
        target: auto
        threshold: 0.5%
        base: auto

ignore:
  - "**/testdata/**"
  - "docs/**"
  - "tools/**"
  - "*.md"