# golangci-lint configuration for Figgo
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional linters for code quality
    - bodyclose
    - dogsled
    - dupl
    - copyloopvar
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

  disable:
    # Disabled as they can be too strict or noisy
    - exhaustive
    - gochecknoglobals
    - godox
    - err113
    - nestif
    - testpackage
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  dupl:
    threshold: 100

  lll:
    line-length: 120
    tab-width: 4

  misspell:
    locale: US

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '10'
      - '32'
      - '64'
      - '128'
      - '256'

issues:
  exclude-dirs:
    - vendor
    - testdata
  exclude-files:
    - ".*\\.generated\\.go$"
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - mnd
        - lll

    # Exclude generated files
    - path: \.generated\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - mnd

    # Allow longer lines in Justfile parsing
    - path: cmd/figgo/main\.go
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false