name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: CI (Lint & Test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Run lint
        run: just lint

      - name: Run tests
        run: just test

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

  build:
    name: Build
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build all binaries
        run: |
          # Build all target platforms
          platforms=(
            "linux/amd64"
            "linux/arm64"
            "darwin/amd64"
            "darwin/arm64"
            "windows/amd64"
          )
          
          for platform in "${platforms[@]}"; do
            IFS='/' read -r goos goarch <<< "$platform"
            output="figgo-${goos}-${goarch}"
            
            if [ "$goos" = "windows" ]; then
              output="${output}.exe"
            fi
            
            echo "Building ${output}..."
            GOOS=$goos GOARCH=$goarch go build -v -o "$output" ./cmd/figgo
            ls -la "$output"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: figgo-binaries
          path: figgo-*

  verify-modules:
    name: Verify Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Verify modules
        run: |
          go mod tidy
          go mod verify
          git diff --exit-code go.mod go.sum

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run benchmarks
        run: go test -bench=. -benchmem ./... | tee benchmark.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmark.txt